version: '3'
services:
  minio:
    image: minio/minio
    container_name: pm_minio
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
